# dvc.yaml
stages:
  get_data:
    cmd: python scripts/data.py
    deps:
      - scripts/data.py
    params:
      - retain
    outs:
      - data/initial_data.csv

  fit_model:
    cmd: python scripts/fit.py
    deps:
      - data/initial_data.csv
      - scripts/fit.py
    params:
      - retain
    outs:
      - models/fitted_model.pkl

  evaluate_model:
    cmd: python scripts/evaluate.py
    deps:
      - models/fitted_model.pkl
      - scripts/evaluate.py
    params:
      - retain
    outs:
      - cv_results/cv_res.json